<?php
require_once(dirname(__FILE__).'/../views/_header.html.php');
require_once(dirname(__FILE__).'/../views/_footer.html.php');
require_once(dirname(__FILE__).'/../views/_nav_bar_top.html.php');
require_once(dirname(__FILE__).'/../views/_nav_left.html.php');
require_once(dirname(__FILE__).'/../views/_home.html.php');
require_once(dirname(__FILE__).'/../views/_mailbox.html.php');
require_once(dirname(__FILE__).'/../views/_clubs_forums_listing.html.php');
require_once(dirname(__FILE__).'/../views/_forum.html.php');
require_once(dirname(__FILE__).'/../views/_admin.html.php');
require_once(dirname(__FILE__).'/../views/_send_mail.html.php');
require_once(dirname(__FILE__).'/../views/_read_mail.html.php');
require_once(dirname(__FILE__).'/../views/_about.html.php');
require_once(dirname(__FILE__).'/../views/_error.html.php');
require_once(dirname(__FILE__).'/../views/_javascript_footer.html.php');
?>